### ISSUE TITLE
Cant find object 'LeadershipPACs' !

### ISSUE THREAD

**Issue by ahmedmohiduet** [cschnaars/FEC-Scraper-Toolbox#1]
I just run my fec_scraper_toolbox_sql_objects.sql and my sqlcmd giving this errors:

D:\FEC-Scraper\FEC-Scraper-Toolbox>sqlcmd -S .\SQLEXPRESS -i fec_scraper_toolbox_sql_objects.sql
Changed database context to 'FEC'.
Msg 208, Level 16, State 1, Server MOHI08-WIN7\SQLEXPRESS, Procedure vwCongressRoster_WithLPACs, Line 104
Invalid object name 'LeadershipPACs'.

Am I missing something?

**Comment by cschnaars** [comment]
You'll need to comment out the CREATE VIEW definition for vwCongressRoster_WithLPACs and either comment out or revise the definition for the usp_GetCongressRoster stored procedure.

I have a table in my database (LeadershipPACs) to track legislators' leadership PACs. This is not part of the Toolbox, however. The FEC data is lousy for tracking leadership PACs. For a while, I was manually curating those PACs but gave up after several months.

I'll try to update the fec_scraper_toolbox_sql_objects.sql file in the next week or two, but this should be all you need to get everything to run. Thanks for bringing this to my attention, and please ping me if you have any more problems.

**Comment by ahmedmohiduet** [comment]
Thank you cschnaars!
I actually tried it and it finally worked! :)
But I have some more issues with parse_reports scripts. Please have a look at my other issues I have openned
