### ISSUE TITLE
Getting exception 'ransID field too long'

### ISSUE THREAD

**Issue by ahmedmohiduet** [cschnaars/FEC-Scraper-Toolbox#4]
My parse_reporsts.py giving object 'sys' not found error:
819099  SC      SC/10.4171      16      SC/10   IncurredDt      none    CCYYMMDD
819099  SC      SC/10.4172      17      SC/10   IncurredDt      none    CCYYMMDD
819099  SC      SC/10.6798      18      SC/10   IncurredDt      none    CCYYMMDD
819099  SC      SC/10.4330      19      SC/10   IncurredDt      none    CCYYMMDD
819099  SC      SC/10.6799      20      SC/10   IncurredDt      none    CCYYMMDD
819099  SC      SC/10.6801      21      SC/10   IncurredDt      none    CCYYMMDD
819099  SC      SC/10.6802      22      SC/10   IncurredDt      none    CCYYMMDD
819099  SC      SC/10.6803      23      SC/10   IncurredDt      none    CCYYMMDD
819099  SC      SC/10.6885      24      SC/10   IncurredDt      NONE    CCYYMMDD
819100  SC      L907    3744    SC/10   IncurredDt      None    CCYYMMDD
819100  SC      L920    3745    SC/10   IncurredDt      None    CCYYMMDD
('TransID field too long.', 819106, 3, {'City': 'Los Alamos', 'DonorCandID': '', 'Zip': '87544', 'CommID':
'C00493486', 'BkRefSchdNm': '', 'ContPurpCd': '', 'StAbbr': 'NM', 'DonorCommID': '', 'DonorCandLName': '',
'BkRefTransID': '', 'ContLName': 'Shin', 'DonorCandSfx': '', 'DonorCandSt': '', 'DonorCandMName': '', 'Dono
rCandDist': '', 'ContOrgNm': '', 'ContMName': '', 'ContPurpDesc': '', 'DonorCandFName': '', 'ContFullName':
 '', 'ConduitZip': '', 'DonorCandPfx': '', 'Occ': '', 'ContSfx': '', 'DonorCandFullName': '', 'EntTp': 'IND
', 'ConduitState': '', 'SIorSLRef': '', 'LineNbr': 'SA11AI', 'ConduitNm': '', 'DonorCandOfc': '', 'Emp': ''
, 'ContAmt': '50.00', 'ContFName': 'Lisa', 'ConduitAddr1': '', 'ContPfx': '', 'ContDt': '20120529', 'Condui
tAddr2': '', 'ElecCd': '', 'ContAgg': '150.00', 'DonorCommNm': '', 'Addr2': '', 'Addr1': '637 47th St', 'El
ecDesc': '', 'MemoCd': '', 'TransID': 'CAPE00000000000002905', 'ConduitCity': '', 'MemoTxt': ''})
Traceback (most recent call last):
  File "parse_reports.py", line 4630, in <module>
    linedata = check_row_data_sch_a(linedata, imageid, linenbr, filehdrdata['NmDelim'], filehdrdata['DtFmt'
])
  File "parse_reports.py", line 2466, in check_row_data_sch_a
    sys.exit(("TransID field too long.", image, rownbr, data))
NameError: global name 'sys' is not defined

Am I missing something!

**Comment by cschnaars** [comment]
The database limits the size of the transaction ID field (TransID) to 20 characters. In the data row you listed, the ID is 21 characters long. I have found 125 rows spread across only 12 reports where the transaction ID is too long: up to 36 characters. They are:
- 771820
- 801548
- 818783
- 825857
- 827117
- 833550
- 837926
- 840792
- 842034
- 842035
- 850188
- 853540

You will either have to increase the size of the TransID field in the tables for schedules A, B, D and E as well as Text to allow 36 characters, ignore these files or manually edit the transaction ID fields to allow up to 36 characters. I will update the .sql file to change these fields to varchar(36).

**Comment by cschnaars** [comment]
I have increased the maximum size of the TransID and BkRefTransID fields to 36 characters in the tables referenced above.
